Turning off python 3.3 in travis for now – Tornado no longer supports it
because

    ImportError: Tornado requires an up-to-date SSL module. This means
    Python 2.7.9+ or 3.4+ (although some distributions have backported
    the necessary changes to older versions).